---
language: python

python:
  - "3.7"

services:
  - docker

env:
  matrix:
    - image="docker-alpine-openrc"
    - image="docker-alpine-openrc" tag="edge"
    # - namespace="archlinux/" image="base"
    - image="docker-debian-systemd" tag="stable"
    - image="docker-debian-systemd" tag="unstable"
    - image="docker-debian-systemd"
    - image="docker-centos-systemd" tag="7"
    - image="docker-redhat-systemd" tag="7"
    - image="docker-centos-systemd"
    - image="docker-redhat-systemd"
    - image="docker-fedora-systemd"
    - image="docker-fedora-systemd" tag="rawhide"
    - image="docker-opensuse-systemd"
    - image="docker-ubuntu-systemd" tag="rolling"
    - image="docker-ubuntu-systemd" tag="devel"
    - image="docker-ubuntu-systemd"

matrix:
  allow_failures:
    - env: image="docker-alpine-openrc" tag="edge"
    - env: image="docker-debian-systemd" tag="unstable"
    - env: image="docker-fedora-systemd" tag="rawhide"
    - env: image="docker-ubuntu-systemd" tag="rolling"
    - env: image="docker-ubuntu-systemd" tag="devel"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "bPMYgxeg7GNaRQnvYIeXLf+rVuKC6w8DM5VEAG8tVis+esPrJFY2u8WGUWF5R4xRxNwq5Dn/A7cXPk3RYz9j2BfaGq0QzeN6C4DyJb8LHhL7VVJypOAkcnNpmwlmWYmR5FSJxRA2i8Tmx3kVc82eLZgMNoFgStg2gMQHDHkiNw2bOiPt/HWycXPkpmfjJkg/JTe7yEkLDzO4PyvUwnI7HjZT5RUrSCsZeMiU5uZMi0VgQ41ypgCSoF6X3tlCQP3vyCo9HGN9PQIrIerwrEArUHxiZXycDuBKRlyDj85hQdZzNTz7xzQ8IA58wcFrN/o9/LEv5T7W+iSlx4c4rZjHRZ1yqjBTPmXIDCHnVFObGkSkfXYjyYgjc9fRGYLjorTJqk7mVL5U/AVd+rrhFtcnuKI1o0c8rvK/gOPvr6dLYkRVxGhethcHOrIQAV1KSt1HaFyUKqL89t5448gMKHEH4Q+bTjVxyR9Y50WBIvSRgvxmzsXfepnXmoxETlcDo0Yk/rgCn4M2LI1AzW/xY3nlEwbG4SRFLDSWkXPh6Hxq6ftGnf9ZdfMv4lXuSYxPgwvMNjb7GUKkAMU61fay5OdPbU6qnhDjqV+tKOGYvbyOlso+bf8FoyD+tl8eyl2yQtCcpjbdLfYaDtj/ETweS3VKdrDNJ6Eu/l2gGhw44CPkcEE="
  email: false
