---
# tasks file for common
- name: load default variables
  include_vars:
    file: default.yml

- name: load os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: set nameserver
  lineinfile:
    path: /etc/resolv.conf
    line: "nameserver {{ item.name }}"
    regexp: "^nameserver "
  with_items:
    - "{{ common_nameservers }}"
  when:
    - common_nameservers is defined
    - ansible_virtualization_type != "kocker"

- name: fill /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
  when:
    - ansible_virtualization_type != "kocker"
